;;; floobits-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from floobits.el

(autoload 'floobits-debug "floobits" "\
Toggle Floobits debug logging." t)
(autoload 'floobits-summon "floobits" "\
Summon all Floobits collaborators to point." t)
(autoload 'floobits-follow-mode-toggle "floobits" "\
Toggle following recent changes in Floobits workspace." t)
(autoload 'floobits-follow-user "floobits" "\
Follow a Floobits collaborator's changes.
Also toggles follow mode (see `floobits-follow-mode-toggle')." t)
(autoload 'floobits-leave-workspace "floobits" "\
Leave the current Floobits workspace." t)
(autoload 'floobits-complete-signup "floobits" "\
Finalize creation of your Floobits account.
If you created a Floobits account via Emacs you must call this
command before you can log in to the website." t)
(autoload 'floobits-share-dir-public "floobits" "\
Create public Floobits workspace and add contents of DIR-TO-SHARE.
If DIR-TO-SHARE does not it exist, it will be created.  If the
directory corresponds to an existing Floobits workspace, the
workspace will be joined instead.

(fn DIR-TO-SHARE)" t)
(autoload 'floobits-share-dir-private "floobits" "\
Create private Floobits workspace and add contents of DIR-TO-SHARE.
If DIR-TO-SHARE does not it exist, it will be created.  If the
directory corresponds to an existing Floobits workspace, the
workspace will be joined instead.

(fn DIR-TO-SHARE)" t)
(autoload 'floobits-join-workspace "floobits" "\
Join an existing Floobits workspace.
Create a new workspace with `floobits-share-dir-public' or
`floobits-share-dir-private', or by visiting http://floobits.com.

(fn FLOOURL)" t)
(autoload 'floobits-workspace-settings "floobits" nil t)
(autoload 'floobits-remove-from-workspace "floobits" "\
Remove PATH from Floobits workspace.
Does not delete file locally.

(fn PATH)" t)
(autoload 'floobits-open-workspace-in-browser "floobits" nil t)
(autoload 'floobits-clear-highlights "floobits" "\
Clear all Floobits highlights." t)
(autoload 'floobits-add-to-workspace "floobits" "\
Add file or directory at PATH to Floobits workspace.

(fn PATH)" t)
(register-definition-prefixes "floobits" '("floobits-"))

;;; End of scraped data

(provide 'floobits-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; floobits-autoloads.el ends here
