;;; jest-test-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jest-test-mode.el

(autoload 'jest-test-mode "jest-test-mode" "\
Toggle jest minor mode.

With no argument, this command toggles the mode. Non-null prefix
argument turns on the mode. Null prefix argument turns off the
mode

This is a minor mode.  If called interactively, toggle the
`Jest-Test mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `jest-test-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'jest-test-run "jest-test-mode" "\
Run the current buffer's file as a test." t)
(autoload 'jest-test-command "jest-test-mode" "\
Format test arguments for FILENAME.

(fn FILENAME)")
(register-definition-prefixes "jest-test-mode" '("jest-test-"))

;;; End of scraped data

(provide 'jest-test-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jest-test-mode-autoloads.el ends here
