;;; graphql-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from graphql.el

(register-definition-prefixes "graphql" '("graphql-"))


;;; Generated autoloads from graphql-examples.el

(register-definition-prefixes "graphql-examples" '("ghubp-"))

;;; End of scraped data

(provide 'graphql-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; graphql-autoloads.el ends here
