;;   -*- mode: lisp-data; -*-
((:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "78/75d1b0-74ca-421b-80e1-c0276b2c6d14" :associated
  (:hash "9e49a1fe2bef89c80a2883addf790033" :file "/Users/chrishowe-jones/emacs-bankruptcy/org/config.org" :inode 14444254)
  :expiry 30 :last-access 1719831709.926913 :last-access-hr "2024-07-01T12:01:49+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "12/2c669a-4b38-4da9-b0c8-14c2ee8aaf89" :associated
  (:hash "70b7d0d3fb6819bf75d2c90ce5c51c72" :file "/Users/chrishowe-jones/.emacs.d/README.org" :inode 851757)
  :expiry 30 :last-access 1719500126.595805 :last-access-hr "2024-06-27T15:55:26+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "de/a3d95a-62a3-4cb2-bbe3-4e6fa3772eb0" :associated
  (:hash "df754a633decb7ed298522d8141035ff" :file "/Users/chrishowe-jones/TerraformForAzure/learning-terraform-3087701/tf-cloud-api-token.org.gpg" :inode 14039201)
  :expiry 30)
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "f2/0a6174-a2dc-49e6-96a0-77a0ba6ea2b7" :associated
  (:hash "926be89d880debbeb4f1f531fd32a9de" :file "/Users/chrishowe-jones/clojure-101/set-up-database.org" :inode 12670652)
  :expiry 30 :last-access 1719495765.251928 :last-access-hr "2024-06-27T14:42:45+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "87/98a91d-97ba-4b3c-a96e-d1c0f7ad9a65" :associated
  (:hash "ba717f0c8ef091af0c91a222eb7010c9" :file "/Users/chrishowe-jones/presentations/graphql/graphql.org" :inode 4878947)
  :expiry 30 :last-access 1718615620.563867 :last-access-hr "2024-06-17T10:13:40+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "ec/f57c56-cfc6-4921-a1be-80f6fd2ff6a5" :associated
  (:hash "07b598dd760c93b1e868d057b4a30345" :file "/Users/chrishowe-jones/presentations/bitr/evolving-prerequisites/evolving-prerequisites.org" :inode 4742847)
  :expiry 30 :last-access 1718614595.418272 :last-access-hr "2024-06-17T09:56:35+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "f4/8b10df-8f5a-4ccf-bc8c-a4b4002b42f5" :associated
  (:hash "3f96fb743d89e963d5f4e1e6ee0bb74d" :file "/Users/chrishowe-jones/presentations/fp_north_east/theneverchangingface.org" :inode 12406111)
  :expiry 30 :last-access 1718617167.556276 :last-access-hr "2024-06-17T10:39:27+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "52/35ef72-0057-451e-887a-f2382e430618" :associated
  (:hash "2dc9e80105bcd29a03f13803ea6ce7ac" :file "/Users/chrishowe-jones/org/gmail-schedule.org_archive" :inode 3913878)
  :expiry 30 :last-access 1719907340.798399 :last-access-hr "2024-07-02T09:02:20+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "30/9907a7-3790-4b64-8c15-8ac6abb92cbb" :associated
  (:hash "4121e284cec1d2de3b0adaf8ee1711fe" :file "/Users/chrishowe-jones/.emacs.d/org/config.org" :inode 9898575)
  :expiry 30 :last-access 1720691661.56516 :last-access-hr "2024-07-11T10:54:21+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "cd/088c93-6c56-4c02-9207-01d2b4d36ea9" :associated
  (:hash "5206fa250d05978f761136715ad65cbf" :file "/Users/chrishowe-jones/org/gmail-schedule.org" :inode 3734291)
  :expiry 30 :last-access 1720691264.063344 :last-access-hr "2024-07-11T10:47:44+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "53/cc0323-50cb-420f-9fbd-ab2a69e9638a" :associated
  (:hash "c13fc77d5fff5eacdf547a8959c00b38" :file "/Users/chrishowe-jones/org/personal.org" :inode 908214)
  :expiry 30 :last-access 1720691264.017758 :last-access-hr "2024-07-11T10:47:44+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "26/1b73d0-b8f0-4086-8056-0c0e977b6ba5" :associated
  (:hash "fbda5be3b05427d10f5a04cd94911670" :file "/Users/chrishowe-jones/org/notes.org" :inode 908194)
  :expiry 30 :last-access 1719910195.51549 :last-access-hr "2024-07-02T09:49:55+0100")
 (:container
  ((index "3.2"))
  :persist-file "82/f2243e-e0d4-4c5a-8a8b-8971ea6ab223" :associated nil :expiry never :last-access 1718191591.484566 :last-access-hr "2024-06-12T12:26:31+0100"))
