;;   -*- mode: lisp-data; -*-
((:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "f2/0a6174-a2dc-49e6-96a0-77a0ba6ea2b7" :associated
  (:hash "926be89d880debbeb4f1f531fd32a9de" :file "/Users/chrishowe-jones/clojure-101/set-up-database.org" :inode 12670652)
  :expiry 30 :last-access 1718723145.510967 :last-access-hr "2024-06-18T16:05:45+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "87/98a91d-97ba-4b3c-a96e-d1c0f7ad9a65" :associated
  (:hash "ba717f0c8ef091af0c91a222eb7010c9" :file "/Users/chrishowe-jones/presentations/graphql/graphql.org" :inode 4878947)
  :expiry 30 :last-access 1718615620.563867 :last-access-hr "2024-06-17T10:13:40+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "ec/f57c56-cfc6-4921-a1be-80f6fd2ff6a5" :associated
  (:hash "07b598dd760c93b1e868d057b4a30345" :file "/Users/chrishowe-jones/presentations/bitr/evolving-prerequisites/evolving-prerequisites.org" :inode 4742847)
  :expiry 30 :last-access 1718614595.418272 :last-access-hr "2024-06-17T09:56:35+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "f4/8b10df-8f5a-4ccf-bc8c-a4b4002b42f5" :associated
  (:hash "3f96fb743d89e963d5f4e1e6ee0bb74d" :file "/Users/chrishowe-jones/presentations/fp_north_east/theneverchangingface.org" :inode 12406111)
  :expiry 30 :last-access 1718617167.556276 :last-access-hr "2024-06-17T10:39:27+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "52/35ef72-0057-451e-887a-f2382e430618" :associated
  (:hash "1d7cf5744ff5014c10834b4fa3953f1f" :file "/Users/chrishowe-jones/org/gmail-schedule.org_archive" :inode 3913878)
  :expiry 30 :last-access 1718612566.206851 :last-access-hr "2024-06-17T09:22:46+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "30/9907a7-3790-4b64-8c15-8ac6abb92cbb" :associated
  (:hash "a0d4c2239a9b84663a872727300a9439" :file "/Users/chrishowe-jones/.emacs.d/org/config.org" :inode 9898575)
  :expiry 30 :last-access 1718723359.674389 :last-access-hr "2024-06-18T16:09:19+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "cd/088c93-6c56-4c02-9207-01d2b4d36ea9" :associated
  (:hash "963f116af9112bcde9fd8fc628ed39af" :file "/Users/chrishowe-jones/org/gmail-schedule.org" :inode 3734291)
  :expiry 30 :last-access 1718784322.881638 :last-access-hr "2024-06-19T09:05:22+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "53/cc0323-50cb-420f-9fbd-ab2a69e9638a" :associated
  (:hash "c13fc77d5fff5eacdf547a8959c00b38" :file "/Users/chrishowe-jones/org/personal.org" :inode 908214)
  :expiry 30 :last-access 1718784322.335684 :last-access-hr "2024-06-19T09:05:22+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "26/1b73d0-b8f0-4086-8056-0c0e977b6ba5" :associated
  (:hash "057ba3f8c00e249378a1829fad10f9bb" :file "/Users/chrishowe-jones/org/notes.org" :inode 908194)
  :expiry 30 :last-access 1718784322.20362 :last-access-hr "2024-06-19T09:05:22+0100")
 (:container
  ((index "3.2"))
  :persist-file "82/f2243e-e0d4-4c5a-8a8b-8971ea6ab223" :associated nil :expiry never :last-access 1718191591.484566 :last-access-hr "2024-06-12T12:26:31+0100"))
