;;   -*- mode: lisp-data; -*-
((:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "78/75d1b0-74ca-421b-80e1-c0276b2c6d14" :associated
  (:hash "64491501b5af3388e2a59749e3af6967" :file "/Users/chrishowe-jones/emacs-bankruptcy/org/config.org" :inode 16995795)
  :expiry 30 :last-access 1719831709.926913 :last-access-hr "2024-07-01T12:01:49+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "de/a3d95a-62a3-4cb2-bbe3-4e6fa3772eb0" :associated
  (:hash "df754a633decb7ed298522d8141035ff" :file "/Users/chrishowe-jones/TerraformForAzure/learning-terraform-3087701/tf-cloud-api-token.org.gpg" :inode 14039201)
  :expiry 30)
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "f2/0a6174-a2dc-49e6-96a0-77a0ba6ea2b7" :associated
  (:hash "926be89d880debbeb4f1f531fd32a9de" :file "/Users/chrishowe-jones/clojure-101/set-up-database.org" :inode 12670652)
  :expiry 30 :last-access 1719495765.251928 :last-access-hr "2024-06-27T14:42:45+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "52/35ef72-0057-451e-887a-f2382e430618" :associated
  (:hash "2dc9e80105bcd29a03f13803ea6ce7ac" :file "/Users/chrishowe-jones/org/gmail-schedule.org_archive" :inode 3913878)
  :expiry 30 :last-access 1719907340.798399 :last-access-hr "2024-07-02T09:02:20+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "30/9907a7-3790-4b64-8c15-8ac6abb92cbb" :associated
  (:hash "3c8583e7db4f9a57b1bd0f1a5740ab1f" :file "/Users/chrishowe-jones/otfrom-org-emacs/org/config.org" :inode 9898575)
  :expiry 30 :last-access 1721041728.094382 :last-access-hr "2024-07-15T12:08:48+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "cd/088c93-6c56-4c02-9207-01d2b4d36ea9" :associated
  (:hash "1ed3713ab13d174e9aba841e8ba5548d" :file "/Users/chrishowe-jones/org/gmail-schedule.org" :inode 3734291)
  :expiry 30 :last-access 1720714601.948025 :last-access-hr "2024-07-11T17:16:41+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "53/cc0323-50cb-420f-9fbd-ab2a69e9638a" :associated
  (:hash "c13fc77d5fff5eacdf547a8959c00b38" :file "/Users/chrishowe-jones/org/personal.org" :inode 908214)
  :expiry 30 :last-access 1721311056.396264 :last-access-hr "2024-07-18T14:57:36+0100")
 (:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "26/1b73d0-b8f0-4086-8056-0c0e977b6ba5" :associated
  (:hash "fbda5be3b05427d10f5a04cd94911670" :file "/Users/chrishowe-jones/org/notes.org" :inode 908194)
  :expiry 30 :last-access 1721311056.323704 :last-access-hr "2024-07-18T14:57:36+0100")
 (:container
  ((index "3.2"))
  :persist-file "82/f2243e-e0d4-4c5a-8a8b-8971ea6ab223" :associated nil :expiry never :last-access 1718191591.484566 :last-access-hr "2024-06-12T12:26:31+0100"))
