;;; meghanada-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from company-meghanada.el

(autoload 'meghanada-company-enable "company-meghanada" "\
Enable auto completion with company.")
(register-definition-prefixes "company-meghanada" '("company-meghanada" "make-icon-hash" "meghanada--" "substring--candidate"))


;;; Generated autoloads from eldoc-meghanada.el

(autoload 'eldoc-meghanada-setup "eldoc-meghanada" "\
Set up eldoc function and enable 'eldoc-mode'." t)
(autoload 'meghanada-eldoc-enable "eldoc-meghanada" "\
Enable eldoc for meghanada-mode.")
(register-definition-prefixes "eldoc-meghanada" '("eldoc-meghanada--"))


;;; Generated autoloads from flycheck-meghanada.el

(autoload 'meghanada-flycheck-enable "flycheck-meghanada" "\
Enable flycheck for meghanada-mode.")
(register-definition-prefixes "flycheck-meghanada" '("flycheck-meghanada-"))


;;; Generated autoloads from meghanada.el

(autoload 'meghanada-install-server "meghanada" "\
Install meghanada-server's jar file from bintray ." t)
(autoload 'meghanada-update-server "meghanada" "\
Update meghanada-server's jar file from bintray ." t)
(autoload 'meghanada-server-start "meghanada" "\
Start the meghanada server." t)
(autoload 'meghanada-server-kill "meghanada" "\
Kill the meghanada server." t)
(autoload 'meghanada-client-direct-connect "meghanada" "\
Connect the client to a server that is already running." t)
(autoload 'meghanada-client-connect "meghanada" "\
Start the server and connect the client" t)
(autoload 'meghanada-client-disconnect "meghanada" "\
Disconnecting the client." t)
(autoload 'meghanada-restart "meghanada" "\
Restart meghanada server and client." t)
(autoload 'meghanada-mode "meghanada" "\
A better java development mode for Emacs (minor-mode).

\\{meghanada-mode-map}

This is a minor mode.  If called interactively, toggle the
`Meghanada mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `meghanada-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "meghanada" '("meghanada-"))

;;; End of scraped data

(provide 'meghanada-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; meghanada-autoloads.el ends here
