;;; company-emacs-eclim-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-emacs-eclim.el

(autoload 'company-emacs-eclim-setup "company-emacs-eclim" "\
Convenience function that adds ‘company-emacs-eclim’ to the list of available company backends.")
(autoload 'company-emacs-eclim "company-emacs-eclim" "\
Eclim `company' completion backend.

See `company' for explanation of COMMAND and ARG.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-emacs-eclim" '("company-emacs-eclim-"))

;;; End of scraped data

(provide 'company-emacs-eclim-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-emacs-eclim-autoloads.el ends here
