;;; align-cljlet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from align-cljlet.el

(autoload 'align-cljlet "align-cljlet" "\
Align a let form so that the bindings neatly align into columns" t)
(register-definition-prefixes "align-cljlet" '("acl-" "defroute-columns"))

;;; End of scraped data

(provide 'align-cljlet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; align-cljlet-autoloads.el ends here
